apiVersion: v1
kind: Service
metadata:
  name: analytical-playground
spec:
  type: NodePort       # For local testing, use LoadBalancer in cloud
  selector:
    app: analytical-playground
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
